services:
  mattermost:
    image: mattermost/mattermost-team-edition
    environment:
      MM_USERNAME: admin
      MM_PASSWORD: admin
      MM_DBNAME: mattermost
      MM_SQLSETTINGS_DATASOURCE: postgres://bour:bour@35.239.186.51:5432/bour?sslmode=disable&connect_timeout=10
    ports:
      - 8065:8065